include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    omit_local_variable_types: false