analyzer:
  exclude:
    - lib/**/*.g.dart

  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    
  plugins:
    - dart_code_metrics

dart_code_metrics:
    anti-patterns:
        - long-method
        - long-parameter-list
    metrics:
        cyclomatic-complexity: 25
        maximum-nesting-level: 5
        number-of-parameters: 4
        source-lines-of-code: 50

    rules:
        - newline-before-return:
            severity: style
        - no-boolean-literal-compare
        - no-empty-block
        - prefer-trailing-comma
        - prefer-conditional-expressions
        - no-equal-then-else
    metrics-exclude:
        - test/**
        - lib/**/*.g.dart

linter:
  rules:
    deprecated_member_use_from_same_package: false
    deprecated_member_use: false
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    always_specify_types: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_slow_async_io: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    curly_braces_in_flow_control_structures: true
    camel_case_types: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    null_closures: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    prefer_for_elements_to_map_fromIterable: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    valid_regexps: true