name: circuit_breaker
description: Circuit Breaker
version: 1.0.0
homepage: https://github.com/DouglasMedeiros/circuit-breaker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.0