name: circuit_breaker
description: Implementation of the Circuit Breaker Design Pattern for HTTP requests
version: 1.0.1
homepage: https://github.com/DouglasMedeiros/circuit-breaker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.4.0
  http: ^0.13.3
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.0