name: circuit_breaker
description: Circuit Breaker
version: 1.0.0
homepage: https://github.com/DouglasMedeiros/circuit-breaker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: