name: circuit_breaker
description: Implementation of the Circuit Breaker Design Pattern for HTTP requests
version: 1.0.3
homepage: https://github.com/DouglasMedeiros/circuit-breaker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
  http: ^0.13.3
  meta: ^1.4.0

dev_dependencies:
  test: ^1.16.0